Debugging Documentation
Open-Systems-Pharmacology/developer-docs pull request #8
Opened 2023-07-07 13:29 UTC by georgeDaskalakis

2023-07-10 10:49 UTC, rwmcintosh requested changes
We need to add the new scripts that enable you to use your local Core builds in local application builds. This has never worked for you, but maybe it will with your new computer.

Let's get it working for you, and as we go, add it to this document.

2023-07-17 07:36 UTC, georgeDaskalakis commented on c-code-specifics/debugging.md
> +![Right click on OSPSuite.Starter project and select "Setup as startup project".](../assets/images/setting as startup project.jpg)
corrected

2023-07-17 10:21 UTC, Yuri05 commented on c-code-specifics/debugging.md
> +![Right click on OSPSuite.Starter project and select "Setup as startup project".](../assets/images/setting as startup project.jpg)
something is still wrong with the images: when I open the document 
https://github.com/Open-Systems-Pharmacology/developer-docs/blob/Debugging-Docu/c-code-specifics/debugging.md 
I still don't see any image

2023-07-17 10:24 UTC, Yuri05 commented on c-code-specifics/debugging.md
> +![Right click on OSPSuite.Starter project and select "Setup as startup project".](../assets/images/setting as startup project.jpg)
whitespace encoding maybe?
e.g. use `setting%20as%20startup%20project.png` instead of `setting as startup project.png`

2023-07-18 08:13 UTC, merged